name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy-to-gh-pages:
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."

      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - run: npm ci

      - run: npm run build:ci -- --base-href /dart-board/ --deploy-url /dart-board/

      - name: Add a 404 workaround # https://angular.io/guide/deployment#server-configuration
        working-directory: dist/dart-board/browser
        run: cp index.html 404.html

      - name: Deploy to GitHub Pages
        if: success()
        uses: JamesIves/github-pages-deploy-action@v4.6.3
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/dart-board/browser # The folder the action should deploy.
          clean: true # Automatically remove files from the target branch
